server:
  port: 9001
# demo: true
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grape?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    # druid 数据库连接池配置
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 1
      max-wait: 60000

# mybatis-plus 配置
mybatis-plus:
  # 别名定义包
  typeAliasesPackage: com.gitee.starblues.grape.repository.databases.entity
  mapperLocations: classpath*:/com/gitee/starblues/grape/repository/databases/mapper/xml/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger 接口配置, 详细见: https://doc.xiaominfo.com/knife4j/documentation/enhance.html
knife4j:
  enable: true
  setting:
    enableDebug: true

# 系统核心配置
system:
  # 超级管理员编码
  superRoleCode: super_admin
  # 是否启用swagger
  swaggerEnable: true
  # jwt 签名key
  jwtSigningKey: defaultSigningKey
  # 不需要授权的接口地址匹配
  noAuthPathPatterns:

# 插件的配置
plugin:
  # 插件运行模式. dev: 开发环境, prod: 生产环境
  runMode: dev
  # 是否启用插件
  enable: true
  # 插件存放的目录
  pluginPath: ./grape-plugins
  # 生产环境下, 插件文件的路径. 只在生产环境下生效
  pluginConfigFilePath:
  # 插件rest接口前缀
  pluginRestPathPrefix: /plugins/
  # 在卸载插件后, 备份插件的目录
  backupPluginPath: backupPlugin
  # 上传的插件所存储的临时目录
  uploadTempPath: temp
  # 禁用的插件id, 禁用后系统不会启动该插件. 为Set集合. 配置案例如下:
  # disablePluginIds:
  #   - disable-id1
  #   - disable-id2
  disablePluginIds:

# web界面配置
web:
  webLocation: classpath:/web/
  # web 界面的配置
  config:
    serverUrl:
    passwordEncryption: true
    clientId: admin_client
    clientSecret: f640e16a951b4109a88cf0fcd4d66a63